const { x, y, z } = require('./Statement')

module.exports = {
  'xN': [
    { if: [], then: z.not.d2 },
    { if: [ x.not.d2 ], then: y.d2 },
    { if: [ x.d2 ], then: y.not.d2 },
    { if: [ y.not.d2 ], then: x.d2 },
    { if: [ y.d2 ], then: x.not.d2 },
    { if: [ x.d2 ], then: x.d4 },
    { if: [ y.d2 ], then: y.d4 },
    { if: [ x.d4 ], then: x.d2 },
    { if: [ y.d4 ], then: y.d2 },
    { if: [ x.d3 ], then: y.not.d3 },
    { if: [ x.not.d3 ], then: y.d3 },
    { if: [ y.d3 ], then: x.not.d3 },
    { if: [ y.not.d3 ], then: x.d3 },
    { if: [ x.d4 ], then: y.not.d4 },
    { if: [ x.not.d4 ], then: y.d4 },
    { if: [ y.d4 ], then: x.not.d4 },
    { if: [ y.not.d4 ], then: x.d4 },
    { if: [ x.d5 ], then: y.not.d5 },
    { if: [ x.d5 ], then: z.not.d5 },
    { if: [ y.d5 ], then: x.not.d5 },
    { if: [ y.d5 ], then: z.not.d5 },
    { if: [ z.d5 ], then: x.not.d5 },
    { if: [ z.d5 ], then: y.not.d5 },
    { if: [ x.not.d5, y.not.d5 ], then: z.d5 },
    { if: [ x.not.d5, z.not.d5 ], then: y.d5 },
    { if: [ y.not.d5, z.not.d5 ], then: x.d5 }
  ],
  'x2': [
    { if: [], then: x.d2 },
    { if: [], then: y.d2 },
    { if: [], then: z.d2 },
    { if: [ x.d3 ], then: y.not.d3 },
    { if: [ x.not.d3 ], then: y.d3 },
    { if: [ y.d3 ], then: x.not.d3 },
    { if: [ y.not.d3 ], then: x.d3 },
    { if: [ x.d4 ], then: y.not.d4 },
    { if: [ x.not.d4 ], then: y.d4 },
    { if: [ y.d4 ], then: x.not.d4 },
    { if: [ y.not.d4 ], then: x.d4 },
    { if: [ x.d5 ], then: y.not.d5 },
    { if: [ x.d5 ], then: z.not.d5 },
    { if: [ y.d5 ], then: x.not.d5 },
    { if: [ y.d5 ], then: z.not.d5 },
    { if: [ z.d5 ], then: x.not.d5 },
    { if: [ z.d5 ], then: y.not.d5 },
    { if: [ x.not.d5, y.not.d5 ], then: z.d5 },
    { if: [ x.not.d5, z.not.d5 ], then: y.d5 },
    { if: [ y.not.d5, z.not.d5 ], then: x.d5 }
  ],
  'x3': [
    { if: [], then: z.not.d2 },
    { if: [], then: x.d3 },
    { if: [], then: y.d3 },
    { if: [], then: z.d3 },
    { if: [ x.not.d2 ], then: y.d2 },
    { if: [ x.d2 ], then: y.not.d2 },
    { if: [ y.not.d2 ], then: x.d2 },
    { if: [ y.d2 ], then: x.not.d2 },
    { if: [ x.d2 ], then: x.d4 },
    { if: [ y.d2 ], then: y.d4 },
    { if: [ x.d4 ], then: x.d2 },
    { if: [ y.d4 ], then: y.d2 },
    { if: [ x.d4 ], then: y.not.d4 },
    { if: [ x.not.d4 ], then: y.d4 },
    { if: [ y.d4 ], then: x.not.d4 },
    { if: [ y.not.d4 ], then: x.d4 },
    { if: [ x.d5 ], then: y.not.d5 },
    { if: [ x.d5 ], then: z.not.d5 },
    { if: [ y.d5 ], then: x.not.d5 },
    { if: [ y.d5 ], then: z.not.d5 },
    { if: [ z.d5 ], then: x.not.d5 },
    { if: [ z.d5 ], then: y.not.d5 },
    { if: [ x.not.d5, y.not.d5 ], then: z.d5 },
    { if: [ x.not.d5, z.not.d5 ], then: y.d5 },
    { if: [ y.not.d5, z.not.d5 ], then: x.d5 }
  ],
  'x4': [
    { if: [], then: x.d2 },
    { if: [], then: y.d2 },
    { if: [], then: z.d2 },
    { if: [], then: x.d4 },
    { if: [], then: y.d4 },
    { if: [], then: z.d4 },
    { if: [ x.d3 ], then: y.not.d3 },
    { if: [ x.not.d3 ], then: y.d3 },
    { if: [ y.d3 ], then: x.not.d3 },
    { if: [ y.not.d3 ], then: x.d3 },
    { if: [ x.d5 ], then: y.not.d5 },
    { if: [ x.d5 ], then: z.not.d5 },
    { if: [ y.d5 ], then: x.not.d5 },
    { if: [ y.d5 ], then: z.not.d5 },
    { if: [ z.d5 ], then: x.not.d5 },
    { if: [ z.d5 ], then: y.not.d5 },
    { if: [ x.not.d5, y.not.d5 ], then: z.d5 },
    { if: [ x.not.d5, z.not.d5 ], then: y.d5 },
    { if: [ y.not.d5, z.not.d5 ], then: x.d5 }
  ],
  'x5': [
    { if: [], then: z.not.d2 },
    { if: [], then: x.d5 },
    { if: [], then: y.d5 },
    { if: [], then: z.d5 },
    { if: [ x.not.d2 ], then: y.d2 },
    { if: [ x.d2 ], then: y.not.d2 },
    { if: [ y.not.d2 ], then: x.d2 },
    { if: [ y.d2 ], then: x.not.d2 },
    { if: [ x.d2 ], then: x.d4 },
    { if: [ y.d2 ], then: y.d4 },
    { if: [ x.d4 ], then: x.d2 },
    { if: [ y.d4 ], then: y.d2 },
    { if: [ x.d3 ], then: y.not.d3 },
    { if: [ x.not.d3 ], then: y.d3 },
    { if: [ y.d3 ], then: x.not.d3 },
    { if: [ y.not.d3 ], then: x.d3 },
    { if: [ x.d4 ], then: y.not.d4 },
    { if: [ x.not.d4 ], then: y.d4 },
    { if: [ y.d4 ], then: x.not.d4 },
    { if: [ y.not.d4 ], then: x.d4 }
  ],
  'x2 x3': [
    { if: [], then: x.d2 },
    { if: [], then: y.d2 },
    { if: [], then: z.d2 },
    { if: [], then: x.d3 },
    { if: [], then: y.d3 },
    { if: [], then: z.d3 },
    { if: [ x.d4 ], then: y.not.d4 },
    { if: [ x.not.d4 ], then: y.d4 },
    { if: [ y.d4 ], then: x.not.d4 },
    { if: [ y.not.d4 ], then: x.d4 },
    { if: [ x.d5 ], then: y.not.d5 },
    { if: [ x.d5 ], then: z.not.d5 },
    { if: [ y.d5 ], then: x.not.d5 },
    { if: [ y.d5 ], then: z.not.d5 },
    { if: [ z.d5 ], then: x.not.d5 },
    { if: [ z.d5 ], then: y.not.d5 },
    { if: [ x.not.d5, y.not.d5 ], then: z.d5 },
    { if: [ x.not.d5, z.not.d5 ], then: y.d5 },
    { if: [ y.not.d5, z.not.d5 ], then: x.d5 }
  ],
  'x2 x5': [
    { if: [], then: x.d2 },
    { if: [], then: y.d2 },
    { if: [], then: z.d2 },
    { if: [], then: x.d5 },
    { if: [], then: y.d5 },
    { if: [], then: z.d5 },
    { if: [ x.d3 ], then: y.not.d3 },
    { if: [ x.not.d3 ], then: y.d3 },
    { if: [ y.d3 ], then: x.not.d3 },
    { if: [ y.not.d3 ], then: x.d3 },
    { if: [ x.d4 ], then: y.not.d4 },
    { if: [ x.not.d4 ], then: y.d4 },
    { if: [ y.d4 ], then: x.not.d4 },
    { if: [ y.not.d4 ], then: x.d4 }
  ],
  'x3 x4': [
    { if: [], then: x.d2 },
    { if: [], then: y.d2 },
    { if: [], then: z.d2 },
    { if: [], then: x.d3 },
    { if: [], then: y.d3 },
    { if: [], then: z.d3 },
    { if: [], then: x.d4 },
    { if: [], then: y.d4 },
    { if: [], then: z.d4 },
    { if: [ x.d5 ], then: y.not.d5 },
    { if: [ x.d5 ], then: z.not.d5 },
    { if: [ y.d5 ], then: x.not.d5 },
    { if: [ y.d5 ], then: z.not.d5 },
    { if: [ z.d5 ], then: x.not.d5 },
    { if: [ z.d5 ], then: y.not.d5 },
    { if: [ x.not.d5, y.not.d5 ], then: z.d5 },
    { if: [ x.not.d5, z.not.d5 ], then: y.d5 },
    { if: [ y.not.d5, z.not.d5 ], then: x.d5 }
  ],
  'x3 x5': [
    { if: [], then: z.not.d2 },
    { if: [], then: x.d3 },
    { if: [], then: y.d3 },
    { if: [], then: z.d3 },
    { if: [], then: x.d5 },
    { if: [], then: y.d5 },
    { if: [], then: z.d5 },
    { if: [ x.not.d2 ], then: y.d2 },
    { if: [ x.d2 ], then: y.not.d2 },
    { if: [ y.not.d2 ], then: x.d2 },
    { if: [ y.d2 ], then: x.not.d2 },
    { if: [ x.d2 ], then: x.d4 },
    { if: [ y.d2 ], then: y.d4 },
    { if: [ x.d4 ], then: x.d2 },
    { if: [ y.d4 ], then: y.d2 },
    { if: [ x.d4 ], then: y.not.d4 },
    { if: [ x.not.d4 ], then: y.d4 },
    { if: [ y.d4 ], then: x.not.d4 },
    { if: [ y.not.d4 ], then: x.d4 }
  ],
  'x4 x5': [
    { if: [], then: x.d2 },
    { if: [], then: y.d2 },
    { if: [], then: z.d2 },
    { if: [], then: x.d4 },
    { if: [], then: y.d4 },
    { if: [], then: z.d4 },
    { if: [], then: x.d5 },
    { if: [], then: y.d5 },
    { if: [], then: z.d5 },
    { if: [ x.d3 ], then: y.not.d3 },
    { if: [ x.not.d3 ], then: y.d3 },
    { if: [ y.d3 ], then: x.not.d3 },
    { if: [ y.not.d3 ], then: x.d3 }
  ],
  'x2 x3 x5': [
    { if: [], then: x.d2 },
    { if: [], then: y.d2 },
    { if: [], then: z.d2 },
    { if: [], then: x.d3 },
    { if: [], then: y.d3 },
    { if: [], then: z.d3 },
    { if: [], then: x.d5 },
    { if: [], then: y.d5 },
    { if: [], then: z.d5 },
    { if: [ x.d4 ], then: y.not.d4 },
    { if: [ x.not.d4 ], then: y.d4 },
    { if: [ y.d4 ], then: x.not.d4 },
    { if: [ y.not.d4 ], then: x.d4 }
  ],
  'x3 x4 x5': [
    { if: [], then: x.d2 },
    { if: [], then: y.d2 },
    { if: [], then: z.d2 },
    { if: [], then: x.d3 },
    { if: [], then: y.d3 },
    { if: [], then: z.d3 },
    { if: [], then: x.d4 },
    { if: [], then: y.d4 },
    { if: [], then: z.d4 },
    { if: [], then: x.d5 },
    { if: [], then: y.d5 },
    { if: [], then: z.d5 }
  ]
}
